language: node_js
node_js:
  - 'stable'
before_script:
  - npm install -g @angular/cli
script:
  - npm run prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master